### ISSUE TITLE
Tidying data

### ISSUE THREAD

**Issue by luizaandrade** [DevInnovationLab/trainings-public#1]

**Comment by saritart1** [comment]
From what I have learned, it would be good to have a check list when tidying the data (maybe this is on the data cleaning, but I don't know, I am doing it all together):
1. Grouping the variables by family. Usually the family is the section (or module) of the survey. 
2. Renaming (if this wasn't done when programming the survey), the variables so the first letters are form the same family (so it is easier to keep the family when tidying and cleaning each section).
3. Having a "cooked" version of the survey in WIDE (or long if preferred) with the variables with the new names and in their final "storage type".
4. Now, we can do the tidying of the dataset into multiple datasets.
5. Identify a structure of the name of the files you want to save.
6. I think we should mention the importance of Github when tidying and having a clear unique id per dataset (I have it on my Stata code and will create a table on my Github)
7. This is something I want to do but I HAVEN'T --> identify, in the paper survey, in which table is each question so the PI and everyone find it easier to follow.

**Comment by luizaandrade** [comment]
Thanks, Sara, that's super helpful. I think we should have a section that's something like "How to make the workflow easier" and list these things. And then maybe you can present that? Would be good to have some concrete example from your projects of how they help (that is, what happens if you don't have that).

Here are some thoughts on each item:

> 1. Grouping the variables by family. Usually the family is the section (or module) of the survey.

I think by default the "group" would be the unit of observation by default, but I agree doing this by section/module makes it a lot easier when you have a large survey.

> 2. Renaming (if this wasn't done when programming the survey), the variables so the first letters are form the same family (so it is easier to keep the family when tidying and cleaning each section).

I really like the practice of having variables in the same module have the same prefix. However, I am less into the practice of renaming variables. And here's why: I think the clean data should have the same variable names as the questionnaire, so you can easily identify which variable corresponds to which questions, even if that means variables will be called `q107_a3` (whyyyy). 

So I think for this session we should say that keeping this in mind when programming the survey can make your life much easier when tidying, but I would not recommend renaming anything while tidying.

> 3. Having a "cooked" version of the survey in WIDE (or long if preferred) with the variables with the new names and in their final "storage type".

I am not sure what you mean by "cooked", but I usually prefer tidying first and then cleaning (i.e., changing data types). That's because (1) depending on the number of repeat groups, variable types may change (for example, if you have a text question, but only one observation of that question for repeat group number 10, and the value in this observation is -99, then question_10 will be numeric and question_1-9 will be string), and (2) the cleaning code becomes cleaner and more efficient.

> 4. Now, we can do the tidying of the dataset into multiple datasets.

Again, for me the order would be 

1. Import
2. Tidy
3. Clean

> 5. Identify a structure of the name of the files you want to save.

Agree that this should be included

> 6. I think we should mention the importance of Github when tidying and having a clear unique id per dataset (I have it on my Stata code and will create a table on my Github)

Yes, unique IDs are very important and should definitely be mentioned if they are not yet! I am not sure I understand why GitHub is important (other than why GitHub is important in general)

> 7. This is something I want to do but I HAVEN'T --> identify, in the paper survey, in which table is each question so the PI and everyone find it easier to follow.

Agreed
